### ISSUE TITLE
Command args must be string, not list of strings

### ISSUE THREAD

**Issue by 0xAX** [OtpChatBot/Ybot#12]
Command args must be string, not list of strings

**Comment by 0xAX** [comment]
done

**Comment by kaos** [comment]
Well, the args are still a list of strings... (or, a list with one string in it, in this case):

```
11:40:48.281 [info] Command: echo, [" foo"]
```

**Comment by 0xAX** [comment]
@kaos thank you for report, will think how to avoid this

**Comment by kaos** [comment]
I happened to include a fix for it with my other fix for the security issue (which was higher prio for me, anyway).

Not sure if you'd prefer \r\n to be translated to spaces, rather than cut out entirely, though.. ?
