### ISSUE TITLE
Hacker News plugin error

### ISSUE THREAD

**Issue by tgrk** [OtpChatBot/Ybot#17]
22:18 @tgrk Ybott hacker_news
22:19 < Ybott> Traceback (most recent call last):
22:19 < Ybott>   File "/home/wiso/Projects/libs/Ybot/plugins/hacker_news.py", line 38, in <module>
22:19 < Ybott>     print front
22:19 < Ybott> UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 291: 
               ordinal not in range(128)

**Comment by 0xAX** [comment]
Martin, what transport and client are you using? I just tested it with xmpp/psi+ it's ok.

**Comment by tgrk** [comment]
I am using IRC transport (with irssi client).

**Comment by 0xAX** [comment]
I added converting to utf8, please, try last version plugin https://github.com/0xAX/Ybot/blob/master/plugins/hacker_news.py

**Comment by 0xAX** [comment]
When you'll test it, please feedback me result

**Comment by tgrk** [comment]
It works but I came across different issue related to IRC:
21:42 < ybot> Last hacker news:
21:42 < ybot> 1. Getting Started with Django--> http://gettingstartedwithdjango.com/en/lessons/introduction-and-launch
21:42 < ybot> 2. Apple Pulls 500px’s Mobile Apps From The App Store--> http://techcrunch.com/2013/01/22/apple-pulls-500pxs-mobile-apps-from-the-app-store-claiming-its-too-easy-to-search-for-nude-photos/
21:42 < ybot> 3. It’s time all clinical trial results are reported--> http://www.alltrials.net/
21:42 < ybot> 4. Finishing what Aaron Swartz started with PACER--> https://mailman.stanford.edu/pipermail/liberationtech/2013-January/006578.html
21:42 -!- ybot [~ybot@g225089099.adsl.alicedsl.de] has quit [Excess Flood]

There is a problem with flood limit (small delays between every message).

**Comment by 0xAX** [comment]
Ok, thank you for feedback. I tested with irc too, same problem. I will add timer between messages,  and improve hacker_news plugin with two modes: all news from front page and N last news.

**Comment by 0xAX** [comment]
fixed
