### ISSUE TITLE
Unable to connect to IRC using SSL

### ISSUE THREAD

**Issue by tgrk** [OtpChatBot/Ybot#18]
I am not able to connect to IRC (link-net) using SSL.
.....
Start with SSL 
22:28:35.883 [info] Starting IRC transport: irc.config.no, <<"#erlplay">>, ybot

1> Info {ssl_closed,{sslsocket,new_ssl,<0.97.0>}}
...

**Comment by 0xAX** [comment]
What server and port do you try to connect?

**Comment by tgrk** [comment]
I am trying to connect to irc.config.no using port 7000

**Comment by 0xAX** [comment]
I found problem, some servers want got pong after join.

**Comment by tgrk** [comment]
Is it also possible to support a channel key for IRC transport? 

Thank you

**Comment by 0xAX** [comment]
What do you mean? Please, explain more details.

**Comment by 0xAX** [comment]
Yes, i understan what you mean. Yes, i'll make it.

**Comment by 0xAX** [comment]
I added join to channel with key in last commit. Just add your key to config. 

Wait feedback.

Thank you.

**Comment by tgrk** [comment]
Cool it is working.
