### ISSUE TITLE
Ybot stales after some time of inactivity

### ISSUE THREAD

**Issue by alinpopa** [OtpChatBot/Ybot#2]
I've noticed that after a period of time of inactivity, when sending a message to Ybot, the response doesn't reach the chat room. If trying the second time, it works. All other requests sent to Ybot will continue working.
I've debugged the code and it seems that Ybot is calling the gen_tcp:send with the right message, but it doesn't get to the chat room, as I've said.

**Comment by 0xAX** [comment]
Thanks, I'll try to reproduce the error and find out. Can you step by step describe your actions for error reproducing?

**Comment by 0xAX** [comment]
I reproduced bug.

**Comment by alinpopa** [comment]
Nice. I was about giving you the steps.

**Comment by 0xAX** [comment]
fixed
