### ISSUE TITLE
Remove io:format/2 calls

### ISSUE THREAD

**Issue by manpages** [OtpChatBot/Ybot#21]
There is virtually no reason to use io:format for logging if we already use lager in some places.
If you want to have several types of messages (ie being able to hide [info]), consider simply providing lager configuration in ybot.config or something like that.

After all it's really easy to visually miss `Start with SSL` part of the following log:

```
08:31:54.105 [info] Loading plugin(Python): ping
08:31:54.105 [info] Loading plugin(Ruby): chuck
Start with SSL
08:31:54.108 [info] Starting IRC transport: memorici.de #bikiniatoll R2
08:31:54.114 [info] Starting http transport <<"localhost">>:8080
```

**Comment by 0xAX** [comment]
done
