### ISSUE TITLE
Ybot brain/memory

### ISSUE THREAD

**Issue by tgrk** [OtpChatBot/Ybot#32]
Did you think about some data persistence? For example learn something or remember something after restart. I am thinking about adding Mnesia support. Another issue that can not be easily solved is to use that persistence layer by plugins...

**Comment by 0xAX** [comment]
yes, it is necessary, I'm thinking best way to implement this

**Comment by tgrk** [comment]
I would vote for Mnesia, because it is so close to Erlang and therefore there won't be any external dependency. For plugins it is a bit tricky, maybe create service that will provide HTTP API for K/V store build on top of Mnesia. Using that service from plugin will require  only HTTP client.

**Comment by 0xAX** [comment]
Yes, we can add supporting for some different storages and start from Mnesia. For plugins, I think something like rest service which will return json  or other structured data from databases.

**Comment by tgrk** [comment]
Sounds reasonable. I am looking forward to give you a hand with implementation if you want.

**Comment by 0xAX** [comment]
sounds good, now i'm developing a plug-in and stabilization of the main branch, can you start to develop backend with mnesia?

**Comment by tgrk** [comment]
Yes hate to think about a data schema a bit. This is always the tricky part :)

**Comment by 0xAX** [comment]
I created Ybot-mnesia-backend branch, we will pushed there first version with mnesia

**Comment by 0xAX** [comment]
About schema data, first of all we must understand for what tasks we will use data storage. At the begining I think we can made simple key/value as you said

**Comment by tgrk** [comment]
cool

**Comment by tgrk** [comment]
I am thinking about something like:
-record(item, {uuid, plugin, key, value, modified, created}).

or for simplicity just:
-record(item, {key, value, plugin, modified, created}).

What do you think?

**Comment by 0xAX** [comment]
I think the first option is good, uuid need, always need some identification. Only I'm confused about modified, why we need it?

By the way we have simple http interface in Ybot, I can expand it not only for users usage, but as http beige from plugins to ybot and back.

**Comment by 0xAX** [comment]
and another little note when you will make mnesia supporting, if you can, try not depend strongly on the main code. In the future I think we will have many backends for ybot, and we should be able to easily integrate their support into bot

**Comment by tgrk** [comment]
Ok good point modified makes no sense. 

About http interface I have to check you code. You did a lot of new stuff which is great :+1:

I will have to think a bit about how to implement it, but I will take it into account for sure.

Ybot power :) Already looking great

**Comment by 0xAX** [comment]
About http It's very primitive now, but of course we can extend it in either way for our needs.

When we will have storage supporting and ybot cans hold some state, I'll plan to add notifications system. I think it will be cool: Todo lists with timing, Twitter feed updating, github repo updating and etc... from ybot

**Comment by tgrk** [comment]
Looking forward to notifications and other functionality build on top of that :)

**Comment by 0xAX** [comment]
Today I stabilizing code and will releasing stable Ybot-0.3 version. And we can start to develop new features for Ybot.

**Comment by tgrk** [comment]
Cool. I am currently working on first version Mnesia based brain.

**Comment by tgrk** [comment]
BTW I finished brain gen_server with Mnesia support. Today I want to implement REST interface for brain (using Cowboy).

**Comment by 0xAX** [comment]
This is really cool! I added cowboy support and http interface in Ybot. If you will something need more, write me i'll make it.

**Comment by tgrk** [comment]
So I basics of API is ready. Can you take a look at API doc - https://github.com/tgrk/Ybot#ybot-brain-rest-api ? I might continue with a simple Ruby plugin that uses this API.

**Comment by 0xAX** [comment]
great to hear, today i'll surely look at it

**Comment by 0xAX** [comment]
I looked at part of Ybot brain REST api documentation, @tgrk realy great work :cool: You can pull request it i'll read code, will test it, i will merge and we can continue test/develop it further. Soon i will start to build notification system on top of Ybot. Great work Martin. Thank you.
