### ISSUE TITLE
Hacker Help plugin error

### ISSUE THREAD

**Issue by tgrk** [OtpChatBot/Ybot#35]
If I call hacker_help without any argument  I receive this error.

15:39 < tgrk> ybot: hacker_help
15:40 < ybot> Traceback (most recent call last):
15:40 < ybot>   File "plugins/hacker_help.py", line 23, in <module>
15:40 < ybot>     response = urllib2.urlopen(api_url)
15:40 < ybot>   File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
15:40 < ybot>     return _opener.open(url, data, timeout)
15:40 < ybot>   File "/usr/lib/python2.7/urllib2.py", line 407, in open
15:40 < ybot>     response = meth(req, response)
15:40 < ybot>   File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
15:40 < ybot>     'http', request, response, code, msg, hdrs)
15:40 < ybot>   File "/usr/lib/python2.7/urllib2.py", line 445, in error
15:40 < ybot>     return self._call_chain(_args)
15:40 < ybot>   File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
15:40 < ybot>     result = func(_args)
15:40 < ybot>   File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
15:40 < ybot>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
15:40 < ybot> urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by 0xAX** [comment]
Fixed
