### ISSUE TITLE
JSON support for http_transport

### ISSUE THREAD

**Issue by AlexMikhalev** [OtpChatBot/Ybot#40]
It would be good to see Ybot http_transport to support JSON with parsing and reacting on {"message":message"}, while passing all other parameters/keys as arguments to plugin.

**Comment by 0xAX** [comment]
@AlexMikhalev, at that moment you can communicate with Ybot via http with two ways:
1. Send simple http post request with command in body:
   
   > curl -X POST -d "Ybot date" http://localhost:8080
2. Send http post request with application/json header and json body:

``` javascript
{
    "type" : "command_type()", 
    "content": "Ybot haker_news 5"
}
```

Where `command_type()`:
- `broadcast` - Message from `content` field will be sending in all Ybot connected chats.
- `response` -  Ybot parse `contet` field, execute message, execute plugin, and send result back.

**Comment by AlexMikhalev** [comment]
Great, I missed that commit.
