### ISSUE TITLE
Unable to connect to IRC

### ISSUE THREAD

**Issue by tgrk** [OtpChatBot/Ybot#42]
Hi,

  I am not able to connect to any IRC server with following error:
`10:20:21.481 [info] Starting IRC transport: {<<"irc.freenode.net">>,<<>>}, {<<"#erlplay">>,<<>>}, ybot
1> 10:21:08.015 [info] tcp_closed with reason: #Port<0.5592>
10:21:08.015 [error] gen_server <0.106.0> terminated with reason: bad return value: {normal,stop,{state,<<"ybot">>,<<"irc.freenode.net">>,6667,<<>>,<<"#erlplay">>,<<>>,#Port<0.5592>,gen_tcp,false,<0.105.0>,5000}}
10:21:08.076 [error] CRASH REPORT Process <0.106.0> with 0 neighbours exited with reason: bad return value: {normal,stop,{state,<<"ybot">>,<<"irc.freenode.net">>,6667,<<>>,<<"#erlplay">>,<<>>,#Port<0.5592>,gen_tcp,false,<0.105.0>,5000}} in gen_server:terminate/6 line 747
10:21:08.115 [error] Supervisor irc_lib_sup had child irc_lib_client started with {irc_lib_client,start_link,undefined} at <0.106.0> exit with reason bad return value: {normal,stop,{state,<<"ybot">>,<<"irc.freenode.net">>,6667,<<>>,<<"#erlplay">>,<<>>,#Port<0.5592>,gen_tcp,false,<0.105.0>,5000}} in context child_terminated`

A bit strange bug.

Thanks

**Comment by 0xAX** [comment]
I confused with return parameters.

**Comment by tgrk** [comment]
I see :)

BTW I finally had some time to work on REST API for "brain" functionality. Hopefully I will have something working after weekend.

**Comment by 0xAX** [comment]
Great news @tgrk, only i return from trip and Ybot development continues.

**Comment by tgrk** [comment]
Ok I still have problem with connection to IRC. Do you know where should I look to fix that? Or I can wait if it requires some more debugging :)

**Comment by 0xAX** [comment]
Today i will have free time and fix it

**Comment by tgrk** [comment]
Cool no rush just want to ask :)

**Comment by 0xAX** [comment]
@tgrk now i run launched Ybot with IRC. What server/channel/port do you try to connect?

**Comment by 0xAX** [comment]
Please try last version from Ybot/master, it must work.

**Comment by 0xAX** [comment]
@tgrk Server returned `Nickname ybot already in use` with this config.  I generate new nick and try to reconnect with it.

**Comment by tgrk** [comment]
Tested with latest version from master and Erlang R16B01 and works fine.
