### ISSUE TITLE
Unable to compile using rebar

### ISSUE THREAD

**Issue by tgrk** [OtpChatBot/Ybot#43]
I tried to get latest version of Ybot and compile it using rebar, but I got following error.

`
==> Ybot (compile)
ERROR: compile failed while processing /home/wiso/Projects/personal/Ybot: {'EXIT',{{badmatch,{error,eexist}},
         [{rebar_erlc_compiler,doterl_compile,3,[]},
          {rebar_core,run_modules,4,[]},
          {rebar_core,execute,5,[]},
          {rebar_core,process_dir0,6,[]},
          {rebar_core,process_dir,4,[]},
          {rebar_core,process_commands,2,[]},
          {rebar,main,1,[]},
          {escript,run,2,[{file,"escript.erl"},{line,741}]}]}}
`

I cloned repo and run rebar get-deps compile.

**Comment by 0xAX** [comment]
@tgrk what version of erlang do you use? Now i cloned Ybot from master and executed: `./rebar deps && ./rebar compile` with erlang R16A, it's ok. `./rebar get-deps compile` works too.

**Comment by tgrk** [comment]
Ahh I am using Erlang R15B03.. Maybe it is time to upgrade :) I will retest with latest version.

**Comment by 0xAX** [comment]
Ok, i try to build with R15B03

**Comment by tgrk** [comment]
After upgrading to Erlang R16B01 there is no compilation error, but I am still not able to connect to IRC server (config https://gist.github.com/tgrk/5077122#file-gistfile1-erl)
