### ISSUE TITLE
Clean and refactoring of ybot.erl and ybot web-admin

### ISSUE THREAD

**Issue by 0xAX** [OtpChatBot/Ybot#53]
Clean and refactoring of ybot.erl and ybot web-admin

**Comment by tgrk** [comment]
I have one question/suggestion regarding refactoring. I don't like that ybot.erl is gen_server. Maybe it would be nicer to separate functionality in two modules. But this is just an idea.

**Comment by 0xAX** [comment]
@tgrk already i did it, today i'll push changes. :+1:

**Comment by 0xAX** [comment]
Now in progress

**Comment by 0xAX** [comment]
done
