### ISSUE TITLE
Pointing to jiffy's HEAD commit is unstable

### ISSUE THREAD

**Issue by jeremyong** [OtpChatBot/Ybot#58]
Seems to be pointing to the HEAD of the jiffy project which doesn't compile right now.

**Comment by 0xAX** [comment]
Give me please your `./rebar compile` output

**Comment by jeremyong** [comment]
I get the precise bug mentioned at [[https://github.com/davisp/jiffy/issues/39]].

Does it make sense to have rebar point to the latest tag instead?

Thanks

**Comment by 0xAX** [comment]
I haven't gcc-4.8 at that moment,Is it builds successfully with jiffy- 0.8.3?

**Comment by jeremyong** [comment]
Ah you know, gcc-4.8 seems to fail to build jiffy at all. Apologize for not checking. It's too bad the project relies on NIFs for this sort of thing.
