### ISSUE TITLE
XMPP name uses whole jid

### ISSUE THREAD

**Issue by slackhead** [OtpChatBot/Ybot#85]
When connect to a XMPP the name of the bot is its complete jid rather than just Ybot. 

This make tab completion on commands fail, since it doesn't answer when the full jid is used.

Is there a way to add a nickname like in IRC etc?

**Comment by 0xAX** [comment]
Can i close this issue?

**Comment by slackhead** [comment]
I no longer have it so cannot check whether it's still a problem.

Close it and if anyone comes across the same issue they can reopen it.
