### ISSUE TITLE
Can't set short node name! Please check your configuration

### ISSUE THREAD

**Issue by tapickell** [OtpChatBot/Ybot#92]
```
2016-07-16 20:31:29 Can't set short node name!
Please check your configuration
```

This is what I got when trying to run this according to the README.
This may be related to #91 not sure.
I updated the start.sh and console.sh
changing `-sname` to `-name`
This seems to be the fix. 

I am new to Erlang so I am unsure if this is the real fix or if it is just covering something that is a deeper issue.

It would also be nice to have better documentation on the README as to what you can do after running the commands in the CLI.

**Comment by ghost** [comment]
@tapickell Did you figure out the issue, here? Was your solution not correct?

**Comment by tapickell** [comment]
@spacez321 I got pulled away from this have not looked at it in a while.
I think that should have fixed it but not 100% sure.
